### ISSUE TITLE
Prepare image for official status

### ISSUE THREAD

**Issue by pesho** [iojs/docker-iojs#1]
In order to become the _official_ `iojs` image on Docker Hub, we need to make some updates, as well as create docs. The process is described here:

https://github.com/docker-library/official-images
https://github.com/docker-library/docs

**Comment by pesho** [comment]
I've prepared PRs against `docker-library/official-images` and `docker-library/docs`. Please review them before I make the submission:

https://github.com/pesho/iojs-docker-official-images
https://github.com/pesho/iojs-docker-docs

cc @rvagg @wblankenship

**Comment by retrohacker** [comment]
https://github.com/iojs/io.js/issues/446#issuecomment-70403399

:smile:

**Comment by retrohacker** [comment]
@pesho lgtm :+1:

**Comment by retrohacker** [comment]
reopened with #8

**Comment by pesho** [comment]
PRs sent:

https://github.com/docker-library/official-images/pull/409
https://github.com/docker-library/docs/pull/141

**Comment by pesho** [comment]
Closing as we are now [official](https://registry.hub.docker.com/_/iojs/), congrats :grinning:

**Comment by rvagg** [comment]
congrats @pesho & @wblankenship !
