### ISSUE TITLE
Signature warning

### ISSUE THREAD

**Issue by jonathanong** [iojs/docker-iojs#15]
```
gpg: Signature made Tue Jan 20 07:54:40 2015 UTC using RSA key ID 7D83545D
gpg: Good signature from "Rod Vagg <rod@vagg.org>"
gpg:                 aka "Rod Vagg <r@va.gg>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: <is this private?>
```

what does this mean?

**Comment by pesho** [comment]
There is no chain of signatures by trusted keys inside the Docker image leading to this key. That's normal and not really an issue. The purpose of this check, and the fetching of the key from a separate keyserver, is to guard against replacing the key published on https://iojs.org/dist/ (e.g. by compromising the server) after the `Dockerfile` was created.
