### ISSUE TITLE
new PGP key

### ISSUE THREAD

**Issue by rvagg** [iojs/docker-iojs#17]
@chrisdickinson has just done v1.1.0 and it's signed with his key so for these dockerfiles to work they'll also need to pull in his key. All release keys in use will have their fingerprints listed at the bottom of https://github.com/iojs/io.js under each person authorized to release (Chris' will be making its way there shortly). You should just be able to append them together, space-separated at the end of the `gpg` command in the Dockerfile.

**Comment by rvagg** [comment]
9554F04D7259F04124DE6B476D5A82AC7E37093B

so perhaps something like this:

```
# verify gpg and sha256: https://iojs.org/dist/$IOJS_VERSION/SHASUMS256.txt.gpg
# one of:
# 7D83545D "Rod Vagg <rod@vagg.org>"
# 7E37093B "Christopher Dickinson <christopher.s.dickinson@gmail.com>"
RUN gpg --keyserver pool.sks-keyservers.net --recv-keys DD8F2338BAE7501E3DD5AC78C273792F7D83545D 9554F04D7259F04124DE6B476D5A82AC7E37093B
```

**Comment by pesho** [comment]
@rvagg works fine, I'm preparing a PR for the new release
