### ISSUE TITLE
Rename on Docker Hub

### ISSUE THREAD

**Issue by rvagg** [iojs/docker-iojs#2]
```
docker run iojs/docker-iojs:1.0
```

is a bit clunky, can we rename "docker-iojs" on Docker Hub to just "iojs" so it's more like:

```
docker run iojs/iojs:1.0
```

Of course if this becomes "official" it'll be nicer anyway but let's not presume that'll actually happen and optimise for the current case.

Thoughts? I'm assuming it's possible to have differing repo names here and on Docker Hub.

**Comment by pesho** [comment]
+1 on the shorter `iojs/iojs`, but the Docker Hub repo would have to be recreated (AFAIR its id can't be changed).

**Comment by rvagg** [comment]
either way this is pretty awesome, it must be said:

```
$ docker run iojs/docker-iojs:1.0 iojs -pe process.versions
{ http_parser: '2.4',
  node: '1.0.2',
  v8: '3.31.74.1',
  uv: '1.2.1',
  zlib: '1.2.8',
  ares: '1.10.0-DEV',
  modules: '42',
  openssl: '1.0.1k' }
```

**Comment by retrohacker** [comment]
https://registry.hub.docker.com/u/iojs/iojs/ 

Done. Readme updated.
