### ISSUE TITLE
Remove iojs/docker-iojs from docker registry

### ISSUE THREAD

**Issue by retrohacker** [iojs/docker-iojs#22]
The builds are failing since we setup the repo to become an official image. https://registry.hub.docker.com/u/iojs/docker-iojs/builds_history/123497/

Planning on removing the repository this weekend.

List objections here :smile:

**Comment by pesho** [comment]
No objections to list :grinning: Best to have a single canonical repo.

**Comment by retrohacker** [comment]
Deleted :rocket:

**Comment by retrohacker** [comment]
Also deleting https://registry.hub.docker.com/u/iojs/iojs/ in favor of the official repositories.

List any objections here :smile:

**Comment by maxbeatty** [comment]
Just to be crystal clear, you're referring to this official repository https://registry.hub.docker.com/_/iojs/?

**Comment by retrohacker** [comment]
@maxbeatty yes :smile_cat:

**Comment by Starefossen** [comment]
Closing this issue since it has been resolved.
