### ISSUE TITLE
The io.js Built Team WG Proposal

### ISSUE THREAD

**Issue by retrohacker** [iojs/docker-iojs#29]
We are putting together a governance model for the io.js build team, and are proposing that the docker-iojs team be a sub-working group of that team. To be part of this conversation, check out: https://github.com/iojs/build/pull/49

**Comment by pesho** [comment]
I'd like to limit my involvement to just docker-iojs for now, so a separate sub-group sounds good :+1:

**Comment by Starefossen** [comment]
Is there a list of members of the docker-iojs sub-working group some where?

**Comment by retrohacker** [comment]
@Starefossen not at the moment. We are still trying to iron out what it means to be a sub-working group.

We could do a pull request to our own README.md with those actively involved in dev.

**Comment by Starefossen** [comment]
Cool, thanks. I guess I'll hang around and see where it goes :smile:

**Comment by pesho** [comment]
@wblankenship btw what is the rationale for the docker-team being a sub-WG of Build? I don't think they are really related.

**Comment by mikeal** [comment]
FYI, we don't have a provision for "sub-WG" in the governance model. Informally the term has been used for working groups that are basically being bootstrapped out of another WG (this happened with evangelism spinning out of the website WG).

While this behavior isn't documented the working group doc does set the expectation that working groups are basically already running and getting things done prior to being chartered so it's all fine :)

**Comment by pesho** [comment]
Thanks @mikeal 

I think we should at least have a separate GitHub team (@iojs/docker). Not sure if this requires a separate WG as well.

**Comment by mikeal** [comment]
Good idea, either @rvagg or I can set that up whenever you like :)

**Comment by pesho** [comment]
Closing as #39 was implemented instead
