### ISSUE TITLE
Docker Working Group proposal

### ISSUE THREAD

**Issue by pesho** [iojs/docker-iojs#39]
This is a proposal and preliminary discussion about forming a new Docker Working Group within io.js. Refs #29. Working Groups are described [here](https://github.com/iojs/io.js/blob/v1.x/WORKING_GROUPS.md).

Possible WG charter (draft):

> ### Docker WG
> 
> The Docker working group's purpose is to build, maintain, and improve official Docker images for the `io.js` project.
> 
> Its responsibilities are:
> - Keep the official Docker images updated in line with new `io.js` releases
> - Decide and implement image improvements
> - Maintain and improve the images' documentation

We also need at least 3 initial WG members (the more the better IMO). Here is an alphabetical list of possible candidates who have contributed in the past (please respond if you would like/dislike to join):

@hmalphettes
@jlmitch5
@pesho
@rvagg
@Starefossen
@wblankenship

There have also been significant contributions from @jfrazelle, @tianon, @yosifkit from the Docker team, who are of course welcome to join if they wish.

Also /cc @mikeal 

Thoughts?

**Comment by jessfraz** [comment]
You can feel free to continue to ping me on whatever patches etc :) I enjoy
a nice break from the large influx of stuff to docker. But I would hate to
commit to be a maintainer and let you all down when I have other maintainer
responsibilities for the docker project. But do feel free to ping me on
whatever. You all are awesome :D

On Tue, Mar 10, 2015 at 2:28 PM, Peter Petrov notifications@github.com
wrote:

> This is a proposal and preliminary discussion about forming a new Docker
> Working Group within io.js. Refs #29
> https://github.com/iojs/docker-iojs/issues/29. Working Groups are
> described here https://github.com/iojs/io.js/blob/v1.x/WORKING_GROUPS.md
> .
> 
> Possible WG charter (draft):
> 
> Docker WG
> 
> The Docker working group's purpose is to build, maintain, and improve
> official Docker images for the io.js project.
> 
> Its responsibilities are:
> - Keep the official Docker images updated in line with new io.js
>   releases
> - Decide and implement image improvements
> - Maintain and improve the images' documentation
>   
>   We also need at least 3 initial WG members (the more the better IMO).
>   Here is an alphabetical list of possible candidates who have contributed in
>   the past (please respond if you would like/dislike to join):
> 
> @hmalphettes https://github.com/hmalphettes
> @jlmitch5 https://github.com/jlmitch5
> @pesho https://github.com/pesho
> @rvagg https://github.com/rvagg
> @Starefossen https://github.com/Starefossen
> @wblankenship https://github.com/wblankenship
> 
> There have also been significant contributions from @jfrazelle
> https://github.com/jfrazelle, @tianon https://github.com/tianon,
> @yosifkit https://github.com/yosifkit from the Docker team, who are of
> course welcome to join if they wish.
> 
> Also /cc @mikeal https://github.com/mikeal
> 
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iojs/docker-iojs/issues/39.

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by Starefossen** [comment]
I would very much like to be a part of the Docker Working Group :whale:

**Comment by tianon** [comment]
I'd echo what Jess said -- I don't want you guys relying on me too much, but I'm happy to take part and provide input where I can, especially since being involved in changes here helps with the review after the official-images PR (since all the changes and rationale for them are already familiar). :+1:

**Comment by tianon** [comment]
I'd echo what Jess said -- I don't want you guys relying on me too much,
but I'm happy to take part and provide input where I can, especially since
being involved in changes here helps with the review after the
official-images PR (since all the changes and rationale for them are
already familiar). :+1:

**Comment by yosifkit** [comment]
I'll also stick to the sidelines with @tianon; watching so that the official-images PRs can go smoothly.  Feel free to ping and ask questions about the official images if need arise.

**Comment by hmalphettes** [comment]
I would also like to join the Docker WG.

**Comment by pesho** [comment]
Ok, we have the required 3 initial WG members (@hmalphettes, @pesho, @Starefossen). Let's wait 24 more hours, in case more people would like to join, or if there are any other suggestions. After that I'll submit our request to the TC.

**Comment by rosskukulinski** [comment]
@pesho I haven't made any contributions (yet), but I have been following the work done here and would like to volunteer to be a 4th WG member.  I'm also a member of the Evangelism WG.

**Comment by pesho** [comment]
@rosskukulinski thanks for volunteering :+1: I'm ok with you joining as an initial member, if the others agree as well.

**Comment by retrohacker** [comment]
I'm on board :smile:

**Comment by pesho** [comment]
Awesome :+1:

**Comment by hmalphettes** [comment]
+1 from here to @rosskukulinski as an initial member.

**Comment by jlmitch5** [comment]
Yes, I would like to join!  I'm on vacation right now, and I'm sorry for responding at the last minute!

**Comment by pesho** [comment]
Proposal submitted: https://github.com/iojs/io.js/pull/1134

@rosskukulinski sorry, I didn't include you in the initial member list. The [rules](https://github.com/iojs/io.js/blob/v1.x/WORKING_GROUPS.md) for starting a WG say that the initial members "`should be individuals already undertaking the work described in the charter`", I hadn't noticed that before. Of course, you are welcome to join later, after you've had a chance to contribute.

**Comment by rosskukulinski** [comment]
No problem!  I'll continue to lurk and help out where I can.  I have some
designated open source time next week, so you'll hear more from me.

How do g'all usually communicate? iRC? Gittim? Just github issues?

**Comment by retrohacker** [comment]
@rosskukulinski we are communicating primarily through github issues right now. I accidentally created a gitter via https://github.com/iojs/docker-iojs/pull/32 so it exists but is currently unusued.

**Comment by retrohacker** [comment]
I opened a pull request for a governance document for if/when our request to become a wg is approved: https://github.com/iojs/docker-iojs/pull/40

**Comment by Starefossen** [comment]
@wblankenship this was approved by the last TC meeting, wasn't it?

**Comment by rvagg** [comment]
yes

**Comment by retrohacker** [comment]
@Starefossen Will get the final documents updated and ready to go tonight :smile:

**Comment by Starefossen** [comment]
The working group docs has been merged so this issue can now be closed. Should we make a `docker` team and add the members as collaborators for this repo maybe?

**Comment by pesho** [comment]
Yes. This has been requested in https://github.com/iojs/io.js/pull/1134, I'm not sure what's the holdup there. @rvagg @mikeal can one of you guys take a look.

**Comment by retrohacker** [comment]
Let's either keep it open until https://github.com/iojs/io.js/pull/1134 is resolved or open a new issue to track it from this repo.

**Comment by pesho** [comment]
Mission completed :)
