### ISSUE TITLE
Error when building the official image:  x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by oren** [iojs/docker-iojs#45]
`docker build -t oreng/iojs .`

```
INFO[0000] Get https://index.docker.io/v1/repositories/library/iojs/images: x509: certificate signed by unknown authority. 
```

Here is my Dockerfile:

```
FROM iojs:latest
RUN useradd -ms /bin/bash developer
WORKDIR /home/developer
USER developer
```

**Comment by rosskukulinski** [comment]
@oren, which version of Docker are you using?

I just tried to reproduce the issue using Docker version 1.5.0, build a8a31ef

Dockerfile:

```
FROM iojs:latest
RUN useradd -ms /bin/bash developer
WORKDIR /home/developer
USER developer
```

And the build command:

```
[~/tmp/test]$ docker build -t rosskukulinski/iojs .
Sending build context to Docker daemon 2.048 kB
Sending build context to Docker daemon 
Step 0 : FROM iojs:latest
 ---> 3496be7b2088
Step 1 : RUN useradd -ms /bin/bash developer
 ---> Running in c16ef875ddf7
 ---> 1b55659b3299
Removing intermediate container c16ef875ddf7
Step 2 : WORKDIR /home/developer
 ---> Running in 874caaa7b8f9
 ---> 309bc5cd73a5
Removing intermediate container 874caaa7b8f9
Step 3 : USER developer
 ---> Running in b71e2abbfb2c
 ---> b8246a741850
Removing intermediate container b71e2abbfb2c
Successfully built b8246a741850
```

**Comment by rosskukulinski** [comment]
I also don't see the error when I use the --pull flag for docker build:

```
docker build --pull -t rosskukulinski/iojs .
```

**Comment by oren** [comment]
`docker version`

```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

`docker info`

```
Containers: 0
Images: 794
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 794
Execution Driver: native-0.2
Kernel Version: 3.16.0-31-generic
Operating System: Ubuntu 14.10
CPUs: 4
Total Memory: 7.68 GiB
Name: oren
ID: KF2M:UGKG:QTGT:TYXH:P6QQ:QVSI:5AYE:T5I3:KLEA:QCKN:7XUW:3FOG
Username: ogolan
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

**Comment by oren** [comment]
Also `hub create` (using https://github.com/github/hub) gives me similar error:

```
Post https://api.github.com/user/repos: x509: certificate signed by unknown authority 
```

is there a problem with my laptop? I am on ubuntu 14.10

**Comment by Starefossen** [comment]
I'm on Ubuntu 14.04 with Docker v1.0 through v1.5 and have never experienced a similar issue with io.js docker image, nor any other image on the Docker Registry for that sake.

Could you `apt-get update -y && apt-get install -y ca-certificates` and try again just to make sure you are up to date with a up to date certificate root store? :grinning:

**Comment by oren** [comment]
apt-get update -y

```
W: Failed to fetch https://deb.nodesource.com/node/dists/utopic/main/source/Sources  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

**Comment by rosskukulinski** [comment]
that's odd.  I'm wondering if there's something up with NodeSource's nodejs installer script.  CC: @rvagg

**Comment by Starefossen** [comment]
@oren Maybe docker/docker#6474 is of any help? Alos, have a look at [this SO question](http://stackoverflow.com/questions/27536180/docker-on-mac-behind-proxy-that-changes-ssl-certificate), and maybe try setting the `--insecure-registry` docker flag as I suspect this is a host/docker issue, and not the signing of io.js itself.

On a separate not, I would highly recommend you to use a [LTS version](http://www.ubuntu.com/info/release-end-of-life) of Ubuntu :sunrise:

**Comment by oren** [comment]
I `rm /etc/apt/sources.list.d/nodesource.list*`
and now i get: 

```
W: Failed to fetch https://get.docker.com/ubuntu/dists/docker/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

**Comment by oren** [comment]
I am closing this issue since we are talking about it here - https://github.com/docker/docker/issues/6474
