### ISSUE TITLE
1.7 tag not yet latest on dockerhub

### ISSUE THREAD

**Issue by crestenstclair** [iojs/docker-iojs#53]
Dockerhub tag list does not reflect the addition of the 1.7 tag

https://registry.hub.docker.com/_/iojs/tags/manage/

**Comment by Starefossen** [comment]
Yes and no. The `1.7` is in fact there, just not visible on the Docker Hub website (see the proof bellow). The Docker guys are [aware of the issue](https://github.com/docker-library/official-images/pull/664#issuecomment-94532867), and I believe they are working on a fix.

```
$ docker pull iojs:latest
$ docker run -it --rm iojs iojs --version
> v1.7.1
```

**Comment by hmalphettes** [comment]
It is listed now: we can close this issue.

BTW I don't have permissions to act on this github repo: is this something I should request directly somewhere?

**Comment by Starefossen** [comment]
@mikeal Could you add @hmalphettes to the [docker](https://github.com/orgs/iojs/teams/docker) team? He's a part of the initial working group members as per #39 and the [readme](https://github.com/iojs/docker-iojs#people).

**Comment by rvagg** [comment]
not sure who did it or when but there's a pending invite already, @hmalphettes go to https://github.com/orgs/iojs/teams/docker and see if it asks you to join.

**Comment by hmalphettes** [comment]
Thanks @rvagg and @Starefossen : somehow I had missed the email.
Cheers!
