### ISSUE TITLE
Joining the Node.JS Foundation

### ISSUE THREAD

**Issue by Starefossen** [iojs/docker-iojs#58]
io.js TC meeting 2015-05-13 voted for joining the Node.JS Foundation, meeting notes are @ iojs/io.js#1700 and the video is @ http://www.youtube.com/watch?v=UbYiFLf7MpU. As per iojs/io.js#1705 all repos and related working groups will be moved to the new "nodejs" org.

> The impact on Working Groups is that they will also be moved in to the "nodejs" org and become part of the Foundation. However, since the Working Groups are autonomous they have the ability to relocate and detach from the Foundation and that is their right. If there are concerns within your Working Group(s) about this move, please discuss it and come to a decision according to the governance procedures you have set up.

So without further ado; should the Docker Working Group join the Node.JS Foundation or not?

**Comment by pesho** [comment]
Definitely +1 for joining.

We also need to decide how to handle the merging of io.js/Node.js docker images in the future (after the first converged release). Specifically:
- How will the new image be called? `node` or `nodejs`?
- Which GitHub repo for the sources? The current one makes the most sense probably, but it will need to be renamed, and the branches from [joyent/docker-node](https://github.com/joyent/docker-node) will have to be merged (at least the ones which will be LTS-supported).
- @chorrell has been maintaining the Node image, he should be invited into this WG

**Comment by Starefossen** [comment]
Definitely +1 for joining from me as well. 

> - How will the new image be called? node or nodejs?

The current image on Docker Hub is called [`node`](https://registry.hub.docker.com/_/node/), I would suggest we stick with that.

> - Which GitHub repo for the sources? The current one makes the most sense probably, but it will need to be renamed, and the branches from joyent/docker-node will have to be merged (at least the ones which will be LTS-supported).

+1 for renaming the current one and merging in maintained joyent/docker-node versions. I see joient/docker-node has a `: wheezy` image tag that iojs/docker-iojs has not.

> - @chorrell has been maintaining the Node image, he should be invited into this WG

+1 from me as well.

**Comment by yosifkit** [comment]
Just a quick +1 on keeping the name as `node` on the Docker hub.  The Hub doesn't really have alias name support or any way to cleanly redirect one image repo to another, though you could poke support@docker.com to make sure they know you want alias naming (ie, `node` and `nodejs`).

**Comment by Starefossen** [comment]
Closing since the converge has been completed.
