### ISSUE TITLE
Missing iojs 2.3.0 image

### ISSUE THREAD

**Issue by lo1tuma** [iojs/docker-iojs#68]
Hi, 

io.js 2.3.0 was released a few days ago, but there is still no 2.3.0 image in the official docker registry.

**Comment by Starefossen** [comment]
I'm on it – sorry for the wait :snail:

**Comment by lo1tuma** [comment]
Thank you :beers:.

**Comment by Starefossen** [comment]
Ok, this has been submitted to the Docker Library.
