### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by tianon** [iojs/docker-iojs#70]
Is 1.8 still "supported"?  ie, if there's a problem discovered with 1.8.2, will there be a 1.8.3?

If it is still supported, is there some documentation somewhere pointing to supported versions (especially with EOL dates)?

**Comment by Starefossen** [comment]
Yes, io.js v1.x is still supported; nodejs/io.js#1736 is a work in progress backport of changes from v2.

The process of long term support is being discussed by the @nodejs/lts working group (https://github.com/nodejs/lts/issues) and will probably be finalised before the next major release of Node.JS is ready.

**Comment by tianon** [comment]
Nice, thanks for clarifying! :heart:
