### ISSUE TITLE
npm WARN cannot run in wd node-gyp

### ISSUE THREAD

**Issue by corbinu** [iojs/docker-iojs#72]
I am canot get node-gyp rebuild to run as an install step within the docker container:

npm install @corbinu/couchbase

gives the error
npm WARN cannot run in wd node-gyp @corbinu/couchbase@2.0.11 node-gyp rebuild

Any ideas?

**Comment by Starefossen** [comment]
This is a `npm` issue npm/npm#3497 since the Docker image runs as root by default.

You can either run the image as a non-root user or `npm install --unsafe-perm`.

**Comment by corbinu** [comment]
OK so perhaps I should issue a pull request to here then to set the default .npmrc to have 

unsafe-perm = true

Or would it be better to open an issue with npm? 

Is it possible to configure NPM with an environment var? maybe issue a PR there that detect something like NPM_UNSAFE_PERM=true and then set that by default in the iojs and node docker containers?

**Comment by Starefossen** [comment]
Yes, setting this via environment variables would be the best. Not sure if we should do this by default since it introduces some security issues. 

We want to investigate how to best run these images under a non-root user.
